[package]
name = "royalguard"
version = "0.1.0"
authors = ["kingbri <bdashore3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio  = { version = "0.2", features = ["macros", "time", "process"] }
tracing-subscriber = "0.2.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dashmap = "4.0.0-rc6"
futures = "0.3"
reqwest = "0.10"
regex = "1.4.1"

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "current"
default-features = true
features = ["model", "collector", "rustls_backend"]

[dependencies.sqlx]
version = "0.4.1"
default-features = false
features = ["runtime-tokio-rustls", "macros", "postgres", "uuid", "offline"]

[target.'cfg(linux)'.dependencies.openssl]
version = "0.10"
features = ["vendored"]

[patch.crates-io.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "current"
default-features = true
features = ["collector", "rustls_backend"]
