// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RoyalGuard.Helpers.Data;

namespace RoyalGuard.Migrations
{
    [DbContext(typeof(RoyalGuardContext))]
    [Migration("20200508142316_RoleTable")]
    partial class RoleTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("RoyalGuard.Helpers.Data.DeleteTimeInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("DeleteTime")
                        .HasColumnType("bigint");

                    b.Property<decimal>("GuildInfoGuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildInfoGuildId");

                    b.ToTable("DeleteTimeStore");
                });

            modelBuilder.Entity("RoyalGuard.Helpers.Data.GuildInfo", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("MuteChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("MutedRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Prefix")
                        .HasColumnType("text");

                    b.HasKey("GuildId");

                    b.ToTable("GuildInfoStore");
                });

            modelBuilder.Entity("RoyalGuard.Helpers.Data.Mute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("MuteTime")
                        .HasColumnType("bigint");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("Mutes");
                });

            modelBuilder.Entity("RoyalGuard.Helpers.Data.NewMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildInfoGuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("LeaveMessage")
                        .HasColumnType("text");

                    b.Property<List<ulong>>("RolesList")
                        .HasColumnType("numeric(20,0)[]");

                    b.Property<string>("WelcomeMessage")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GuildInfoGuildId");

                    b.ToTable("NewMembers");
                });

            modelBuilder.Entity("RoyalGuard.Helpers.Data.Warn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("GuildInfoGuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("WarnNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GuildInfoGuildId");

                    b.ToTable("Warns");
                });

            modelBuilder.Entity("RoyalGuard.Helpers.Data.WelcomeRoles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("GuildInfoGuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildInfoGuildId");

                    b.ToTable("WelcomeRoles");
                });

            modelBuilder.Entity("RoyalGuard.Helpers.Data.DeleteTimeInfo", b =>
                {
                    b.HasOne("RoyalGuard.Helpers.Data.GuildInfo", "GuildInfo")
                        .WithMany("DeleteTimeCollection")
                        .HasForeignKey("GuildInfoGuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoyalGuard.Helpers.Data.NewMember", b =>
                {
                    b.HasOne("RoyalGuard.Helpers.Data.GuildInfo", "GuildInfo")
                        .WithMany("NewMemberCollection")
                        .HasForeignKey("GuildInfoGuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoyalGuard.Helpers.Data.Warn", b =>
                {
                    b.HasOne("RoyalGuard.Helpers.Data.GuildInfo", "GuildInfo")
                        .WithMany("WarnCollection")
                        .HasForeignKey("GuildInfoGuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoyalGuard.Helpers.Data.WelcomeRoles", b =>
                {
                    b.HasOne("RoyalGuard.Helpers.Data.GuildInfo", "GuildInfo")
                        .WithMany("WelcomeRoleCollection")
                        .HasForeignKey("GuildInfoGuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
